using UnityEngine;
using TMPro;
using System.Collections;

public class CauldronState : MonoBehaviour
{
	[Header("Live State UI Elements")]
	[SerializeField] private TextMeshProUGUI currentPotencyText;
	[SerializeField] private TextMeshProUGUI currentInstabilityText;

	[Header("Target Recipe UI Elements")]
	[SerializeField] private TextMeshProUGUI targetPotencyText;
	[SerializeField] private TextMeshProUGUI targetInstabilityText;

	private PotionCauldron cauldron;

	void Start()
	{
		StopAllCoroutines();
		// Start a coroutine to find the cauldron safely, 
		// just in case it takes a split second to spawn over the network.
		StartCoroutine(InitializeDisplay());
	}

	private IEnumerator InitializeDisplay()
	{
		// Wait until the cauldron is found in the scene
		while (cauldron == null)
		{
			cauldron = FindFirstObjectByType<PotionCauldron>();
			yield return new WaitForSeconds(0.1f);
		}

		// 1. Display the Target Recipe (Generated by the server on spawn)
		if (targetPotencyText != null)
			targetPotencyText.text = $"Target Potency: {cauldron.targetPotency.Value}";

		if (targetInstabilityText != null)
			targetInstabilityText.text = $"Target Instability: {cauldron.targetInstability.Value}";

		// 2. Initialize the Live Mixing State values (usually 0 at start)
		UpdateText(cauldron.currentPotency.Value, cauldron.currentInstability.Value);

		// 3. Subscribe to live changes so the text updates when the Librarian drops ingredients
		cauldron.currentPotency.OnValueChanged += OnPotencyChanged;
		cauldron.currentInstability.OnValueChanged += OnInstabilityChanged;
	}

	void OnDestroy()
	{
		// Unsubscribe to protect memory stability when changing scenes
		if (cauldron != null)
		{
			cauldron.currentPotency.OnValueChanged -= OnPotencyChanged;
			cauldron.currentInstability.OnValueChanged -= OnInstabilityChanged;
		}
	}

	private void OnPotencyChanged(int oldValue, int newValue)
	{
		UpdateText(newValue, cauldron.currentInstability.Value);
	}

	private void OnInstabilityChanged(int oldValue, int newValue)
	{
		UpdateText(cauldron.currentPotency.Value, newValue);
	}

	private void UpdateText(int currentPotency, int currentInstability)
	{
		if (currentPotencyText != null)
		{
			currentPotencyText.text = $"Current Potency: {currentPotency}";
		}

		if (currentInstabilityText != null)
		{
			currentInstabilityText.text = $"Current Instability: {currentInstability}";

			// Give the Apprentice visual warning cues: turn text red if unstable!
			currentInstabilityText.color = currentInstability > cauldron.targetInstability.Value ? Color.red : Color.green;
		}
	}
}
